export enum stateProcedure {
  INSCRITO = 'INSCRITO',
  EN_REVISION = 'EN REVISION',
  OBSERVADO = 'OBSERVADO',
  CONCLUIDO = 'CONCLUIDO',
  ANULADO = 'ANULADO',
  SUSPENDIDO = 'SUSPENDIDO',
  RETIRADO = 'RETIRADO',
  ABANDONO = 'ABANDONO',
}
